services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pass123
      MYSQL_DATABASE: springtutorialjpa
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: my-user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: